version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: ls -l
    volumes:
      - ~/repos/personal/django_tutorial:/app
    ports:
      - "8000:8000"
